name: "Current Time 2"
author: "Gerred Dillon <hello@gerred.org>, Shahar Frank<srfrnk@gmail.com>"
description: "Get the current time with format"
branding:
  icon: clock
  color: blue
outputs:
  time:
    description: "The time this action was run"
runs:
  using: "node12"
  main: "index.js"
