name: Test the action
on: 
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@test
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          O: "${{ steps.current-time.outputs }}"
          TIME: "${{ O.time }}"
          R_TIME: "${{ O.readableTime }}"
          F_TIME: "${{ O.formattedTime }}"
          YEAR: "${{ O.year }}"
          DAY: "${{ O.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
